export type MenuItem = {
  id: string;
  name: string;
  price: number | string; // string for items like "350/200"
  isVeg: boolean;
  isSpicy?: boolean;
  image?: string;
};

export type MenuCategory = {
  id: string;
  name: string;
  items: MenuItem[];
};

export const menuData: MenuCategory[] = [
  {
    id: "salads-sprouts",
    name: "SALADS & SPROUTS",
    items: [
      { id: "sprouts", name: "Sprouts", price: 80, isVeg: true },
      { id: "vegetable-sprouts", name: "Vegetable Sprouts", price: 90, isVeg: true },
      { id: "paneer-sprouts", name: "Paneer Sprouts", price: 100, isVeg: true },
      { id: "boiled-egg-sprouts", name: "Boiled Egg Sprouts", price: 120, isVeg: false },
      { id: "special-sprouts", name: "Special Sprouts", price: 120, isVeg: true },
      { id: "paneer-salad", name: "Paneer Salad", price: 170, isVeg: true },
      { id: "chicken-salad", name: "Chicken Salad", price: 180, isVeg: false },
      { id: "protein-salad", name: "Protein Salad", price: 150, isVeg: true },
    ],
  },
  {
    id: "breakfast-snacks",
    name: "BREAKFAST & SNACKS",
    items: [
      { id: "pohe", name: "Pohe", price: 30, isVeg: true },
      { id: "upma", name: "Upma", price: 30, isVeg: true },
      { id: "sabudana-khichadi", name: "Sabudana Khichadi", price: 30, isVeg: true },
      { id: "idli", name: "Idli", price: 35, isVeg: true },
      { id: "medu-wada", name: "Medu Wada", price: 40, isVeg: true },
      { id: "misal-pav", name: "Misal Pav", price: 60, isVeg: true, image: "/images/misal-pav.webp" },
      { id: "pav-bhaji", name: "Pav Bhaji", price: 80, isVeg: true },
    ],
  },
  {
    id: "dosa-uttappa",
    name: "DOSA & UTTAPPA",
    items: [
      { id: "sada-dosa", name: "Sada Dosa", price: 45, isVeg: true },
      { id: "masala-dosa", name: "Masala Dosa", price: 60, isVeg: true, image: "/images/masala-dosa.webp" },
      { id: "cheese-masala-dosa", name: "Cheese Masala Dosa", price: 90, isVeg: true },
      { id: "mysore-masala-dosa", name: "Mysore Masala Dosa", price: 85, isVeg: true },
      { id: "schezwan-cut-dosa", name: "Schezwan Cut Dosa", price: 80, isVeg: true, isSpicy: true },
      { id: "cut-dosa", name: "Cut Dosa", price: 80, isVeg: true },
      { id: "onion-uttappa", name: "Onion Uttappa", price: 60, isVeg: true },
      { id: "onion-cheese-uttappa", name: "Onion Cheese Uttappa", price: 85, isVeg: true },
    ],
  },
  {
    id: "chaat-sandwiches",
    name: "CHAAT & SANDWICHES",
    items: [
      { id: "samosa-2-pcs", name: "Samosa (2 pcs)", price: 50, isVeg: true },
      { id: "chat-samosa", name: "Chat Samosa", price: 70, isVeg: true },
      { id: "dahi-wade", name: "Dahi Wade", price: 80, isVeg: true },
      { id: "chutney-cheese-sw", name: "Chutney Cheese S/W", price: 60, isVeg: true },
      { id: "veg-cheese-sw", name: "Veg Cheese S/W", price: 80, isVeg: true },
      { id: "corn-cheese-sw", name: "Corn Cheese S/W", price: 80, isVeg: true },
      { id: "paneer-tikka-cheese-sw", name: "Paneer Tikka Cheese S/W", price: 90, isVeg: true },
      { id: "chicken-tikka-cheese-sw", name: "Chicken Tikka Cheese S/W", price: 100, isVeg: false },
      { id: "chicken-schezwan-cheese-sw", name: "Chicken Schezwan Cheese S/W", price: 110, isVeg: false, isSpicy: true },
    ],
  },
  {
    id: "soups",
    name: "SOUPS",
    items: [
      { id: "tomato-soup", name: "Tomato Soup", price: 85, isVeg: true },
      { id: "hot-sour-soup-veg", name: "Hot & Sour Soup (Veg)", price: 85, isVeg: true, isSpicy: true },
      { id: "manchow-soup-veg", name: "Manchow Soup (Veg)", price: 85, isVeg: true },
      { id: "veg-clear-soup", name: "Veg Clear Soup", price: 85, isVeg: true },
      { id: "lemon-coriander-soup", name: "Lemon Coriander Soup", price: 90, isVeg: true },
      { id: "palak-soup", name: "Palak Soup", price: 90, isVeg: true },
      { id: "chicken-manchow-soup", name: "Chicken Manchow Soup", price: 90, isVeg: false },
      { id: "chicken-hot-sour-soup", name: "Chicken Hot & Sour Soup", price: 90, isVeg: false, isSpicy: true },
      { id: "chicken-clear-soup", name: "Chicken Clear Soup", price: 90, isVeg: false },
    ],
  },
  {
    id: "pasta-maggi",
    name: "PASTA & MAGGI",
    items: [
      { id: "white-sauce-pasta", name: "White Sauce Pasta", price: 140, isVeg: true },
      { id: "alfredo-cheese-pasta", name: "Alfredo Cheese Pasta", price: 150, isVeg: true },
      { id: "mix-sauce-pasta", name: "Mix Sauce Pasta", price: 160, isVeg: true },
      { id: "paneer-cheese-pasta", name: "Paneer Cheese Pasta", price: 170, isVeg: true },
      { id: "chicken-cheese-pasta", name: "Chicken Cheese Pasta", price: 180, isVeg: false },
      { id: "special-cheese-pasta", name: "Special Cheese Pasta", price: 180, isVeg: true },
      { id: "classic-pasta", name: "Classic Pasta", price: 180, isVeg: true },
      { id: "red-sauce-pasta", name: "Red Sauce Pasta", price: 140, isVeg: true },
      { id: "lemon-chicken-pasta", name: "Lemon Chicken Pasta", price: 180, isVeg: false },
      { id: "maggi", name: "Maggi", price: 50, isVeg: true },
      { id: "vegetable-maggi", name: "Vegetable Maggi", price: 55, isVeg: true },
      { id: "butter-maggi", name: "Butter Maggi", price: 60, isVeg: true },
      { id: "egg-maggi", name: "Egg Maggi", price: 60, isVeg: false },
      { id: "cheese-maggi", name: "Cheese Maggi", price: 70, isVeg: true },
    ],
  },
  {
    id: "momos-nuggets",
    name: "MOMOS & NUGGETS",
    items: [
      { id: "veg-nuggets-10-pcs", name: "Veg Nuggets 10 Pcs", price: 110, isVeg: true },
      { id: "veg-steam-momos-5-pcs", name: "Veg Steam Momos 5 Pcs", price: 70, isVeg: true, image: "/images/momos.webp" },
      { id: "veg-fry-momos-5-pcs", name: "Veg Fry Momos 5 Pcs", price: 70, isVeg: true, image: "/images/momos.webp" },
      { id: "veg-chilli-momos", name: "Veg Chilli Momos", price: 120, isVeg: true, isSpicy: true, image: "/images/momos.webp" },
      { id: "chicken-nuggets-10-pcs", name: "Chicken Nuggets 10 Pcs", price: 120, isVeg: false },
      { id: "chicken-steam-momos-5-pcs", name: "Chicken Steam Momos 5 Pcs", price: 80, isVeg: false, image: "/images/momos.webp" },
      { id: "chicken-fry-momos-5-pcs", name: "Chicken Fry Momos 5 Pcs", price: 80, isVeg: false, image: "/images/momos.webp" },
      { id: "chicken-chilli-momos", name: "Chicken Chilli Momos", price: 130, isVeg: false, isSpicy: true, image: "/images/momos.webp" },
    ],
  },
  {
    id: "veg-starters",
    name: "VEG STARTERS",
    items: [
      { id: "gobi-manchurian", name: "Gobi Manchurian Dry/Gravy", price: 130, isVeg: true },
      { id: "veg-manchurian", name: "Veg Manchurian Dry/Gravy", price: 130, isVeg: true },
      { id: "paneer-chilly", name: "Paneer Chilly Dry/Gravy", price: 130, isVeg: true, isSpicy: true },
      { id: "veg-crispy", name: "Veg Crispy", price: 140, isVeg: true },
      { id: "honey-chilli-potato", name: "Honey Chilli Potato", price: 140, isVeg: true, isSpicy: true },
      { id: "honey-chilli-mushroom", name: "Honey Chilli Mushroom", price: 140, isVeg: true, isSpicy: true },
      { id: "stuffed-mushroom-chilli-dry", name: "Stuffed Mushroom Chilli Dry", price: 150, isVeg: true, isSpicy: true },
      { id: "dragon-paneer", name: "Dragon Paneer", price: 140, isVeg: true, isSpicy: true },
      { id: "paneer-65", name: "Paneer 65", price: 140, isVeg: true },
      { id: "paneer-tikka", name: "Paneer Tikka", price: 180, isVeg: true },
      { id: "paneer-pudina-tikka", name: "Paneer Pudina Tikka", price: 180, isVeg: true },
      { id: "paneer-shole-kabab", name: "Paneer Shole Kabab", price: 180, isVeg: true },
    ],
  },
  {
    id: "nonveg-starters",
    name: "NON-VEG STARTERS",
    items: [
      { id: "chicken-chilly", name: "Chicken Chilly Dry/Gravy", price: 150, isVeg: false, isSpicy: true },
      { id: "chicken-manchurian", name: "Chicken Manchurian Dry/Gravy", price: 150, isVeg: false },
      { id: "chicken-65", name: "Chicken 65", price: 150, isVeg: false },
      { id: "hot-garlic-chicken", name: "Hot Garlic Chicken", price: 150, isVeg: false, isSpicy: true },
      { id: "chicken-salt-pepper", name: "Chicken Salt Pepper", price: 150, isVeg: false },
      { id: "crispy-chicken", name: "Crispy Chicken", price: 160, isVeg: false },
      { id: "lemon-chicken", name: "Lemon Chicken", price: 150, isVeg: false },
      { id: "chicken-sathe", name: "Chicken Sathe", price: 150, isVeg: false },
      { id: "black-pepper-chicken", name: "Black Pepper Chicken", price: 150, isVeg: false, isSpicy: true },
      { id: "chicken-lollypop", name: "Chicken Lollypop", price: 150, isVeg: false },
    ],
  },
  {
    id: "paneer-mains",
    name: "PANEER MAINS",
    items: [
      { id: "paneer-bhurji", name: "Paneer Bhurji", price: 150, isVeg: true },
      { id: "paneer-masala", name: "Paneer Masala", price: 130, isVeg: true },
      { id: "mutter-paneer", name: "Mutter Paneer", price: 130, isVeg: true },
      { id: "palak-paneer", name: "Palak Paneer", price: 130, isVeg: true },
      { id: "paneer-butter-masala", name: "Paneer Butter Masala", price: 140, isVeg: true, image: "/images/paneer-butter-masala.webp" },
      { id: "kadai-paneer", name: "Kadai Paneer", price: 130, isVeg: true },
      { id: "paneer-acharya", name: "Paneer Acharya", price: 130, isVeg: true },
      { id: "paneer-mushroom-masala", name: "Paneer Mushroom Masala", price: 130, isVeg: true },
      { id: "tez-paneer", name: "Tez Paneer", price: 130, isVeg: true, isSpicy: true },
      { id: "paneer-kheema", name: "Paneer Kheema", price: 150, isVeg: true },
      { id: "paneer-lababdar", name: "Paneer Lababdar", price: 140, isVeg: true },
      { id: "paneer-patiyala", name: "Paneer Patiyala", price: 140, isVeg: true },
      { id: "paneer-handi", name: "Paneer Handi", price: 170, isVeg: true },
      { id: "paneer-kurchan", name: "Paneer Kurchan", price: 140, isVeg: true },
      { id: "paneer-kofta", name: "Paneer Kofta", price: 140, isVeg: true },
      { id: "paneer-passanda", name: "Paneer Passanda", price: 140, isVeg: true },
      { id: "paneer-pakoda", name: "Paneer Pakoda", price: 130, isVeg: true },
      { id: "paneer-lahori", name: "Paneer Lahori", price: 130, isVeg: true },
      { id: "paneer-tikka-ms", name: "Paneer Tikka M/S", price: 140, isVeg: true },
      { id: "paneer-muglai", name: "Paneer Muglai", price: 190, isVeg: true },
      { id: "kaju-paneer-masala", name: "Kaju Paneer Masala", price: 140, isVeg: true },
    ],
  },
  {
    id: "veg-mains",
    name: "VEG MAINS",
    items: [
      { id: "veg-handi", name: "Veg Handi", price: 160, isVeg: true },
      { id: "shiv-bhaji", name: "Shiv Bhaji", price: 130, isVeg: true },
      { id: "veg-kolhapuri", name: "Veg Kolhapuri", price: 120, isVeg: true, isSpicy: true },
      { id: "lasuni-palak", name: "Lasuni Palak", price: 130, isVeg: true },
      { id: "aloo-palak", name: "Aloo Palak", price: 120, isVeg: true },
      { id: "aloo-gobi-dry", name: "Aloo Gobi Dry", price: 120, isVeg: true },
      { id: "aloo-mutter", name: "Aloo Mutter", price: 120, isVeg: true },
      { id: "aloo-jeera", name: "Aloo Jeera", price: 120, isVeg: true },
      { id: "aloo-gobi-masala", name: "Aloo Gobi Masala", price: 120, isVeg: true },
      { id: "veg-jaipuri", name: "Veg Jaipuri", price: 130, isVeg: true },
      { id: "sabji-mandi", name: "Sabji Mandi", price: 130, isVeg: true },
      { id: "veg-makhanwala", name: "Veg Makhanwala", price: 130, isVeg: true },
      { id: "kofta-sanj-savera", name: "Kofta Sanj Savera", price: 140, isVeg: true },
      { id: "veg-maratha", name: "Veg Maratha", price: 130, isVeg: true },
      { id: "veg-bhuna", name: "Veg Bhuna", price: 130, isVeg: true },
      { id: "bhendi-fry", name: "Bhendi Fry", price: 130, isVeg: true },
      { id: "aloo-bhendi-fry", name: "Aloo Bhendi Fry", price: 120, isVeg: true },
      { id: "bhendi-masala", name: "Bhendi Masala (Gravy)", price: 120, isVeg: true },
      { id: "mushroom-masala", name: "Mushroom Masala", price: 120, isVeg: true },
      { id: "mushroom-kadai", name: "Mushroom Kadai", price: 120, isVeg: true },
      { id: "mushroom-mutter-masala", name: "Mushroom Mutter Masala", price: 130, isVeg: true },
      { id: "green-peas-masala", name: "Green Peas Masala", price: 120, isVeg: true },
      { id: "green-peas-palak", name: "Green Peas Palak", price: 120, isVeg: true },
      { id: "amritsari-chole", name: "Amritsari Chole", price: 120, isVeg: true },
      { id: "chole-masala", name: "Chole Masala", price: 120, isVeg: true },
      { id: "kadai-sabji", name: "Kadai Sabji", price: 130, isVeg: true },
      { id: "veg-kheema", name: "Veg Kheema", price: 140, isVeg: true },
      { id: "veg-jalfrazi", name: "Veg Jalfrazi", price: 130, isVeg: true },
      { id: "veg-patiyala", name: "Veg Patiyala", price: 130, isVeg: true },
      { id: "veg-lahori", name: "Veg Lahori", price: 130, isVeg: true },
      { id: "damalu-punjabi", name: "Damalu Punjabi", price: 130, isVeg: true },
      { id: "corn-capsicum-masala", name: "Corn Capsicum Masala", price: 130, isVeg: true },
      { id: "kaju-masala", name: "Kaju Masala", price: 170, isVeg: true },
      { id: "kaju-curry", name: "Kaju Curry", price: 170, isVeg: true },
      { id: "copa-special-veg-masala", name: "Copa Special Veg Masala", price: 180, isVeg: true },
      { id: "navratan-korma", name: "Navratan Korma", price: 190, isVeg: true },
      { id: "veg-korma", name: "Veg Korma", price: 140, isVeg: true },
      { id: "dumaloo-kashmiri", name: "Dumaloo Kashmiri", price: 120, isVeg: true },
      { id: "veg-pahadi", name: "Veg Pahadi", price: 140, isVeg: true },
      { id: "baby-corn-masala", name: "Baby Corn Masala", price: 130, isVeg: true },
      { id: "malai-kofta", name: "Malai Kofta", price: 130, isVeg: true },
    ],
  },
  {
    id: "chicken-egg-mains",
    name: "CHICKEN & EGG MAINS",
    items: [
      { id: "chicken-curry", name: "Chicken Curry", price: 140, isVeg: false },
      { id: "chicken-masala", name: "Chicken Masala", price: 140, isVeg: false },
      { id: "chicken-kolhapuri", name: "Chicken Kolhapuri", price: 140, isVeg: false, isSpicy: true },
      { id: "chicken-hyderabadi", name: "Chicken Hyderabadi", price: 140, isVeg: false },
      { id: "chicken-kadai", name: "Chicken Kadai", price: 140, isVeg: false },
      { id: "chicken-butter-masala", name: "Chicken Butter Masala", price: 140, isVeg: false },
      { id: "egg-curry", name: "Egg Curry", price: 120, isVeg: false },
      { id: "egg-masala", name: "Egg Masala", price: 120, isVeg: false },
      { id: "egg-ghotala", name: "Egg Ghotala", price: 130, isVeg: false },
      { id: "chicken-afgani", name: "Chicken Afgani", price: 140, isVeg: false },
      { id: "chicken-lahori", name: "Chicken Lahori", price: 140, isVeg: false },
      { id: "chicken-lababdar", name: "Chicken Lababdar", price: 140, isVeg: false },
      { id: "chicken-banjara", name: "Chicken Banjara M/S", price: 140, isVeg: false },
      { id: "chicken-kheema", name: "Chicken Kheema", price: 150, isVeg: false },
      { id: "chicken-pahadi-masala", name: "Chicken Pahadi Masala", price: 140, isVeg: false },
      { id: "chicken-patiala", name: "Chicken Patiala", price: 150, isVeg: false },
      { id: "chicken-sukka", name: "Chicken Sukka", price: 150, isVeg: false },
      { id: "copa-special-murg-masala", name: "Copa Special Murg Masala", price: 150, isVeg: false },
      { id: "murg-muglai", name: "Murg Muglai", price: 150, isVeg: false },
      { id: "murg-banjara", name: "Murg Banjara", price: 140, isVeg: false },
      { id: "murg-adreki-masala", name: "Murg Adreki Masala", price: 140, isVeg: false },
      { id: "murg-kalimirch-masala", name: "Murg Kalimirch Masala", price: 140, isVeg: false },
      { id: "murg-laara", name: "Murg Laara", price: 150, isVeg: false },
      { id: "murg-malwani-masala", name: "Murg Malwani Masala", price: 160, isVeg: false },
    ],
  },
  {
    id: "eggs",
    name: "EGGS",
    items: [
      { id: "egg-bhurji", name: "Egg Bhurji 2 Bread/Chapati (2 Eggs)", price: 70, isVeg: false },
      { id: "omlet", name: "Omlet 2 Bread/Chapati (2 Eggs)", price: 70, isVeg: false },
      { id: "boiled-eggs", name: "Boiled Eggs (2 Pcs)", price: 30, isVeg: false },
      { id: "masala-boiled-eggs", name: "Masala Boiled Eggs (2 Pcs)", price: 60, isVeg: false },
      { id: "cheese-omlet", name: "Cheese Omlet 2 Bread/Chapati (2 Eggs)", price: 80, isVeg: false },
      { id: "half-full-fry", name: "Half Fry / Full Fry (2 Eggs)", price: 55, isVeg: false },
    ],
  },
  {
    id: "dal",
    name: "DAL",
    items: [
      { id: "dal-fry", name: "Dal Fry", price: 80, isVeg: true },
      { id: "dal-tadka", name: "Dal Tadka", price: 90, isVeg: true },
      { id: "dal-palak", name: "Dal Palak", price: 110, isVeg: true },
      { id: "dal-makhani", name: "Dal Makhani", price: 120, isVeg: true },
    ],
  },
  {
    id: "rice-biryani",
    name: "RICE & BIRYANI",
    items: [
      { id: "veg-biryani", name: "Veg Biryani", price: 140, isVeg: true },
      { id: "veg-hyderabadi-biryani", name: "Veg Hyderabadi Biryani", price: 140, isVeg: true },
      { id: "paneer-biryani", name: "Paneer Biryani", price: 150, isVeg: true },
      { id: "veg-pulav", name: "Veg Pulav", price: 120, isVeg: true },
      { id: "veg-pulav-masala", name: "Veg Pulav (Masala)", price: 120, isVeg: true },
      { id: "paneer-pulav", name: "Paneer Pulav", price: 130, isVeg: true },
      { id: "paneer-pulav-masala", name: "Paneer Pulav (Masala)", price: 140, isVeg: true },
      { id: "green-peas-pulav", name: "Green Peas Pulav", price: 120, isVeg: true },
      { id: "jeera-rice", name: "Jeera Rice", price: 85, isVeg: true },
      { id: "steam-rice", name: "Steam Rice", price: 55, isVeg: true },
      { id: "curd-rice", name: "Curd Rice", price: 100, isVeg: true },
      { id: "dal-khichadi", name: "Dal Khichadi", price: 100, isVeg: true },
      { id: "palak-khichadi", name: "Palak Khichadi", price: 110, isVeg: true },
      { id: "veg-tawa-pulao", name: "Veg Tawa Pulao", price: 130, isVeg: true },
      { id: "paneer-tava-pulao", name: "Paneer Tava Pulao", price: 140, isVeg: true },
      { id: "kashmiri-pulao", name: "Kashmiri Pulao", price: 160, isVeg: true },
      { id: "chicken-biryani", name: "Chicken Biryani", price: 150, isVeg: false, image: "/images/chicken-biryani.webp" },
      { id: "chicken-hyderabadi-biryani", name: "Chicken Hyderabadi Biryani", price: 160, isVeg: false },
      { id: "chicken-biryani-boneless", name: "Chicken Biryani Boneless", price: 170, isVeg: false },
      { id: "chicken-hyd-biryani-boneless", name: "Chicken Hyd Biryani Boneless", price: 180, isVeg: false },
      { id: "chicken-tava-pulao", name: "Chicken Tava Pulao", price: 150, isVeg: false },
      { id: "egg-biryani", name: "Egg Biryani", price: 140, isVeg: false },
    ],
  },
  {
    id: "thali",
    name: "THALI",
    items: [
      { id: "veg-thali", name: "Veg Thali", price: 110, isVeg: true, image: "/images/thali.webp" },
      { id: "egg-thali", name: "Egg Thali", price: 130, isVeg: false },
      { id: "chicken-thali", name: "Chicken Thali", price: 135, isVeg: false },
    ],
  },
  {
    id: "chinese-veg",
    name: "CHINESE (VEG)",
    items: [
      { id: "veg-hakka-noodles", name: "Veg Hakka Noodles", price: 130, isVeg: true },
      { id: "veg-schezwan-noodles", name: "Veg Schezwan Noodles", price: 130, isVeg: true, isSpicy: true },
      { id: "veg-chilli-garlic-noodles", name: "Veg Chilli Garlic Noodles", price: 130, isVeg: true, isSpicy: true },
      { id: "veg-manchurian-schezwan-noodles", name: "Veg Manchurian Schezwan Noodles", price: 130, isVeg: true },
      { id: "veg-chinese-bhel", name: "Veg Chinese Bhel", price: 140, isVeg: true },
      { id: "veg-ginger-noodle", name: "Veg Ginger Noodle", price: 140, isVeg: true },
      { id: "mixed-noodle", name: "Mixed Noodle", price: 150, isVeg: true },
      { id: "pan-fried-noodle", name: "Pan Fried Noodle", price: 160, isVeg: true },
      { id: "veg-maxican-noodle", name: "Veg Mexican Noodle", price: 140, isVeg: true },
      { id: "veg-choumin", name: "Veg Choumin", price: 140, isVeg: true },
      { id: "veg-fried-rice", name: "Veg Fried Rice", price: 130, isVeg: true },
      { id: "veg-schezwan-fried-rice", name: "Veg Schezwan Fried Rice", price: 130, isVeg: true, isSpicy: true },
      { id: "veg-manchurian-fried-rice", name: "Veg Manchurian Fried Rice", price: 130, isVeg: true },
      { id: "veg-manchurian-schezwan-fried", name: "Veg Manchurian Schezwan Fried", price: 130, isVeg: true },
      { id: "mushroom-fried-rice", name: "Mushroom Fried Rice", price: 130, isVeg: true },
      { id: "veg-maxican-rice", name: "Veg Mexican Rice", price: 130, isVeg: true },
      { id: "veg-triple-schezwan-rice", name: "Veg Triple Schezwan Rice", price: 170, isVeg: true, isSpicy: true },
      { id: "veg-hong-kong", name: "Veg Hong Kong Fried Rice/Noodle", price: 140, isVeg: true },
      { id: "veg-singapuri", name: "Veg Singapuri Fried Rice/Noodle", price: 140, isVeg: true },
      { id: "veg-combination", name: "Veg Combination Rice/Noodle", price: 150, isVeg: true },
      { id: "potato-chilly-dry", name: "Potato Chilly Dry", price: 130, isVeg: true, isSpicy: true },
    ],
  },
  {
    id: "chinese-nonveg",
    name: "CHINESE (NON-VEG)",
    items: [
      { id: "chicken-hakka-noodles", name: "Chicken Hakka Noodles", price: 130, isVeg: false },
      { id: "chicken-schezwan-noodles", name: "Chicken Schezwan Noodles", price: 140, isVeg: false, isSpicy: true },
      { id: "chicken-chilli-garlic-noodles", name: "Chicken Chilli Garlic Noodles", price: 140, isVeg: false, isSpicy: true },
      { id: "chicken-maxican-noodles", name: "Chicken Mexican Noodles", price: 150, isVeg: false },
      { id: "chicken-chinese-bhel", name: "Chicken Chinese Bhel", price: 150, isVeg: false },
      { id: "chicken-ginger-noodle", name: "Chicken Ginger Noodle", price: 140, isVeg: false },
      { id: "chicken-choumin", name: "Chicken Choumin", price: 150, isVeg: false },
      { id: "egg-schezwan-noodles", name: "Egg Schezwan Noodles", price: 140, isVeg: false },
      { id: "chicken-fried-rice", name: "Chicken Fried Rice", price: 150, isVeg: false },
      { id: "chicken-schezwan-fried-rice", name: "Chicken Schezwan Fried Rice", price: 150, isVeg: false, isSpicy: true },
      { id: "chicken-maxican-rice", name: "Chicken Mexican Rice", price: 150, isVeg: false },
      { id: "lemon-chicken-rice", name: "Lemon Chicken Rice", price: 150, isVeg: false },
      { id: "chicken-triple-schezwan-rice", name: "Chicken Triple Schezwan Rice", price: 190, isVeg: false, isSpicy: true },
      { id: "egg-fried-rice", name: "Egg Fried Rice", price: 140, isVeg: false },
      { id: "egg-schezwan-fried-rice", name: "Egg Schezwan Fried Rice", price: 140, isVeg: false },
      { id: "chicken-hong-kong", name: "Chicken Hong Kong Fried Rice/Noodle", price: 160, isVeg: false },
      { id: "chicken-singapuri", name: "Chicken Singapuri Fried Rice/Noodle", price: 160, isVeg: false },
      { id: "chicken-combination", name: "Chicken Combination Rice/Noodle", price: 160, isVeg: false },
      { id: "chicken-tometo-rice", name: "Chicken Tomato Rice/Noodle", price: 160, isVeg: false },
      { id: "chicken-green-garlic-dry", name: "Chicken Green Garlic Dry", price: 150, isVeg: false },
      { id: "eggs-chilly-dry", name: "Eggs Chilly Dry", price: 140, isVeg: false, isSpicy: true },
      { id: "lemon-chicken-fried-rice", name: "Lemon Chicken Fried Rice", price: 160, isVeg: false },
    ],
  },
  {
    id: "breads",
    name: "INDIAN BREADS",
    items: [
      { id: "chapati", name: "Chapati", price: 10, isVeg: true },
      { id: "gahu-roti", name: "Gahu Roti", price: 20, isVeg: true },
      { id: "tandoori-roti", name: "Tandoori Roti", price: 16, isVeg: true },
      { id: "naan", name: "Naan", price: 30, isVeg: true },
      { id: "butter-naan", name: "Butter Naan", price: 35, isVeg: true },
      { id: "cheese-garlic-naan", name: "Cheese Garlic Naan", price: 45, isVeg: true },
      { id: "cheese-naan", name: "Cheese Naan", price: 50, isVeg: true },
      { id: "plain-kulcha", name: "Plain Kulcha", price: 25, isVeg: true },
      { id: "butter-kulcha", name: "Butter Kulcha", price: 35, isVeg: true },
      { id: "garlic-onion-kulcha", name: "Garlic Onion Kulcha", price: 40, isVeg: true },
      { id: "onion-kulcha", name: "Onion Kulcha", price: 35, isVeg: true },
      { id: "stuffed-masala-kulcha", name: "Stuffed Masala Kulcha", price: 55, isVeg: true },
      { id: "lachha-paratha", name: "Lachha Paratha", price: 40, isVeg: true },
      { id: "pudina-paratha", name: "Pudina Paratha", price: 30, isVeg: true },
      { id: "makai-roti", name: "Makai Roti", price: 30, isVeg: true },
      { id: "roti-ki-tokri", name: "Roti Ki Tokri", price: 160, isVeg: true },
    ],
  },
  {
    id: "parathas",
    name: "PARATHAS",
    items: [
      { id: "aloo-paratha", name: "Aloo Paratha", price: 85, isVeg: true },
      { id: "gobi-paratha", name: "Gobi Paratha", price: 85, isVeg: true },
      { id: "green-peas-paratha", name: "Green Peas Paratha", price: 85, isVeg: true },
      { id: "aloo-gobi-paratha", name: "Aloo Gobi Paratha", price: 85, isVeg: true },
      { id: "mix-veg-paratha", name: "Mix Veg Paratha", price: 90, isVeg: true },
      { id: "paneer-paratha", name: "Paneer Paratha", price: 100, isVeg: true },
      { id: "cheese-paratha", name: "Cheese Paratha", price: 110, isVeg: true },
      { id: "aloo-cheese-paratha", name: "Aloo Cheese Paratha", price: 110, isVeg: true },
    ],
  },
  {
    id: "tandoor",
    name: "TANDOOR & KEBABS",
    items: [
      { id: "murg-tandoor", name: "Murg Tandoor Full/Half", price: "350/200", isVeg: false },
      { id: "murg-jangli", name: "Murg Jangli Full/Half", price: "350/200", isVeg: false },
      { id: "murg-tikka", name: "Murg Tikka", price: 190, isVeg: false },
      { id: "murg-banjara-tikka", name: "Murg Banjara Tikka", price: 190, isVeg: false },
      { id: "murg-pahadi-tikka", name: "Murg Pahadi Tikka", price: 190, isVeg: false },
      { id: "murg-reshmi-tikka", name: "Murg Reshmi Tikka", price: 200, isVeg: false },
      { id: "murg-malai-tikka", name: "Murg Malai Tikka", price: 200, isVeg: false },
      { id: "murg-sholey-kabab", name: "Murg Sholey Kabab", price: 200, isVeg: false },
      { id: "murg-seek-kabab", name: "Murg Seek Kabab", price: 170, isVeg: false },
      { id: "murg-tandoor-lolipop", name: "Murg Tandoor Lollipop", price: 170, isVeg: false },
      { id: "murg-pudina-tikka", name: "Murg Pudina Tikka", price: 190, isVeg: false },
      { id: "murg-angara-kabab", name: "Murg Angara Kabab", price: 190, isVeg: false },
    ],
  },
  {
    id: "raita-papad",
    name: "RAITA & PAPAD",
    items: [
      { id: "boondi-raita", name: "Boondi Raita", price: 40, isVeg: true },
      { id: "pineapple-raita", name: "Pineapple Raita", price: 50, isVeg: true },
      { id: "sabji-raita", name: "Sabji Raita", price: 40, isVeg: true },
      { id: "masala-papad", name: "Masala Papad", price: 30, isVeg: true },
      { id: "roasted-papad-fry", name: "Roasted Papad Fry", price: 10, isVeg: true },
    ],
  },
  {
    id: "juices",
    name: "JUICES",
    items: [
      { id: "mosambi-juice", name: "Mosambi Juice", price: 30, isVeg: true },
      { id: "orange-juice", name: "Orange Juice", price: 30, isVeg: true },
      { id: "pineapple-juice", name: "Pineapple Juice", price: 30, isVeg: true },
      { id: "watermelon-juice", name: "Watermelon Juice", price: 30, isVeg: true },
      { id: "anar-juice", name: "Anar Juice", price: 40, isVeg: true },
      { id: "apple-juice", name: "Apple Juice", price: 40, isVeg: true },
      { id: "mix-fruit-juice", name: "Mix Fruit Juice", price: 50, isVeg: true },
      { id: "fresh-lime-juice", name: "Fresh Lime Juice", price: 25, isVeg: true },
      { id: "ganga-jamuna", name: "Ganga Jamuna", price: 35, isVeg: true },
      { id: "fruit-plate", name: "Fruit Plate", price: 80, isVeg: true },
      { id: "fruit-salad", name: "Fruit Salad", price: 90, isVeg: true },
    ],
  },
  {
    id: "milkshakes",
    name: "MILKSHAKES & COLD DRINKS",
    items: [
      { id: "apple-milkshake", name: "Apple Milk Shake", price: 40, isVeg: true },
      { id: "mango-milkshake", name: "Mango Milk Shake", price: 40, isVeg: true },
      { id: "banana-milkshake", name: "Banana Milk Shake", price: 35, isVeg: true },
      { id: "chikoo-milkshake", name: "Chikoo Milk Shake", price: 40, isVeg: true },
      { id: "chocolate-milkshake", name: "Chocolate Milk Shake", price: 40, isVeg: true },
      { id: "strawberry-milkshake", name: "Strawberry Milk Shake", price: 40, isVeg: true },
      { id: "rosa-milkshake", name: "Rosa Milk Shake", price: 40, isVeg: true },
      { id: "sitaphal-milkshake", name: "Sitaphal Milk Shake", price: 40, isVeg: true },
      { id: "mix-fruit-milkshake", name: "Mix Fruit Milk Shake", price: 50, isVeg: true },
      { id: "vanilla-milkshake", name: "Vanilla Milk Shake", price: 40, isVeg: true },
      { id: "dry-fruit-milkshake", name: "Dry Fruit Milk Shake", price: 60, isVeg: true },
      { id: "oreo-milkshake", name: "Oreo Milk Shake", price: 80, isVeg: true },
      { id: "cold-coffee", name: "Cold Coffee", price: 30, isVeg: true },
      { id: "lassi", name: "Lassi", price: 40, isVeg: true, image: "/images/lassi.webp" },
      { id: "mango-lassi", name: "Mango Lassi", price: 50, isVeg: true },
    ],
  },
];
